# Site settings
title: Corentin Corde
description: Corentin Corde CV
favicon: /assets/img/me_rtone.jpeg
baseurl:
url: http://konovagit.github.io/
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Corentin Corde
  title: Ingénieur génie Electrique spécialité Embedded System
  address: Lyon, France
  email: corentincorde@orange.fr
  link: http://konovagit.github.io/
  weibo:
  github: konovagit
  twitter: corentincorde
  gavatar: /assets/img/me_rtone.jpeg
  educationHistory:
    - education1:
      organization: Polytech Clermont-Ferrand (CUST)
      degree: Ingénieur en Génie électrique option systèmes informatiques embarqués
      started: 2013
      duration: (2013 - 2016)
      description: 
    - education2: 
      organization: Université Claude Bernard LYON 1
      degree: Diplôme Universitaire de Technologie Génie Electrique et Informatique Industrielle
      started: 2011
      duration: (2011 - 2013)
      description:
    - education3: 
      organization: La Martinière Monplaisir LYON
      degree: Diplôme du Baccalauréat Sciences et Technologies Industrielles option génie Electrotechnique Mention Bien
      started: 2010
      duration: (2010 - 2011)
      description:
  workHistory:
    - work1:
      company: Internship Kingston University 
      location: Penrhyn Rd, Kingston upon Thames, Surrey KT1 2EE, Royaume-Uni
      title: Internship (4ème année d'ingénieur)
      started: 2015
      duration: (3 mois Juin-Aout)
      description: Collaboration avec le Dr Francisco Florez Revuelta pour le projet Européen Ambient Assisted Living. Il s'agit d'un vaste programme pour améliorer la vie des personnes âgées chez eux. Dans ce stage j'ai utilisé la vision par ordinateur et notamment la librairie OpenCV en C++. Le but de mon projet était de tracker des personnes dans une pièce et de déterminer de manière automatique leurs activités. Pour cela j'ai testé et créé différents algorithmes de traitement.
    - work2:
      company: EKIUM 
      location: 5 Allée des Droits de l'Homme, 69500 Bron, France
      title: Stage Technicien Supérieur
      started: 2013
      duration: (3 mois Avril-Juin)
      description: Réalisation d'automatismes et de supervisions pour différents projets. Supervision de VMC et d'alarme incendie pour l'usine Renault à Tanger. Supervision (immotique) pour bâtiment BBC à Lyon (Empreinte centre d'affaires). Lecture de plans, réalisation schémas électriques, réunions et gestion clients.
    - work3:
      company: UCPA CARRE DE SOIE 
      location: 3 Avenue de Bohlen, 69120 Vaulx-en-Velin, France
      title: Animateur Sportif (sur 3 ans)
      started: 2012
      duration: (Tous les mois de Juin de 2012 à 2014)
      description: Encadrement d’un parc de jeux gonflables tous les mois de juillet pour animer le quartier du carré de soie et pour accueillir les enfants qui n'ont pas la chance de partir en vacances. Sécurité, gestion des entrées sorties, manutention du parc, animation.
    - work4:
      company: Scierie DUBOT et FILS   
      location: 63380 –SAINT AVIT
      title: Mission d’intérim Opérateur de scierie
      started: 2011
      duration: (Juillet-Aout)
      description: Premier job d'été. Interim de 2 mois dans une scierie. Travail à la chaine (contraintes de temps et de sécurité), triage du bois et mise sur palette.
    - work5: 
      company: SARL YVES PACCALIN   
      location: 23 rue Louis Cézard 69008 LYON
      title: Stage d'Electricien
      started: 2010
      duration: (Juillet)
      description: Travaux d’électricité sur chantier et particulier. Lecture de schémas électriques, raccord au réseau électrique EDF.
  languages:
    - language1:
      name: Français
      proficiency: Native
    - language2:
      name: English (Toeic:780)
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: C
      percentage: 85%
    - skill2:
      name: C++
      percentage: 75%
    - skill3:
      name: Qt
      percentage: 65%
    - skill4:
      name: SystemC
      percentage: 65%
    - skill5:
      name: VHDL
      percentage: 75%
    - skill6:
      name: OpenCV
      percentage: 75%
    - skill7:
      name: SQL
      percentage: 60%
    - skill8:
      name: Bash
      percentage: 60%
    - skill9:
      name: CAO
      percentage: 75%


    
